# application.yml
server:
  port: 8686
spring:
  application:
    name: book-audit
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: book-audit  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
  #        :${server.port}
  #mongo
  data:
    mongodb:
      uri: mongodb://mongo:27017/books_audit
      username: mongodb
      password: admin
      database: image_books
      profiles:
        active: dev
#kafka
kafka:
  bootstrap-servers: kafka1:9092
  # producer:
  #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    # group-id: my-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.data.mongodb.core: debug
    org.springframework.cloud.consul: DEBUG







