# application.yml
server:
  port: 8787
spring:
  application:
    name: book-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: book-service  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
  #        :${server.port}
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://postgres_container_book:5432/books
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://mongo-1:27017/image_books
      # host: mongo-1
      username: mongodb
      password: admin
      # database: image_books
      # port: 27017
      profiles:
        active: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl.auto: update
        cache:
          caches:
            -name: booksCache
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
# liquibase.properties
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  contexts: development, production
  default-schema: book
# kafka
kafka:
    bootstrap-servers: kafka1:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # consumer:
    #   group-id: my-group
    #   auto-offset-reset: earliest
    #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# logging
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
      org.springframework.data.mongodb.core: debug
      hibernate: debug
      springframework:
        cache: debug
      org.springframework.cloud.consul: DEBUG







