server:
  port: 8585
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul-server.consul.svc.cluster.local
      port: 8501
      discovery:
        # enabled: true  # Enable service discovery
    #     # service-name: gateway  # Optional: Custom service name
    #     # register: true
    #     # # health-check-url: http://gateway:8585/actuator/health
    #     # health-check-url: http://gateway:8585/actuator/health
    #     # # instance-id: ${spring.application.name}:${random.value}:${server.port}
        enabled: true
        register: true
        instanceId: ${spring.application.name}:${server.port}
        healthCheckUrl: http://gateway:8586/actuator/health
        healthCheckInterval: 15s
        preferIpAddress: false
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}:${server.port}
  
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service  # Assuming BOOK-SERVICE is the service ID registered in your service discovery
          predicates:
            - Path=/books/**

        - id: book-service
          uri: lb://book-service  # Assuming BOOK-SERVICE is the service ID registered in your service discovery
          predicates:
            - Path=/image/**

        - id: book-audit
          uri: lb://book-audit # Replace with the correct service ID
          predicates:
            - Method=POST
            - Path=/audit/{bookName}
          filters:
            - RewritePath=/audit/(?<name>.*), /$\{name}

        - id: book-audit
          uri: lb://book-audit
          predicates:
            - Path=/audit/**
#        - id: book-audit
#          uri: lb://book-audit
#          predicates:
#            - Path=/audit/**
#          filters:
#            - RewritePath=/audit/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.data.mongodb.core: debug
    hibernate: debug
    springframework.cache: debug
    org.springframework.cloud.consul: DEBUG
    org.springframework.cloud.gateway: DEBUG